import type { Metadata, Viewport } from "next";
import "./globals.css";
import { RegisterSW } from "@/components/RegisterSW";

const SITE = "https://titanomega-ai.com";

export const metadata: Metadata = {
  metadataBase: new URL(SITE),
  title: "Titan Omega — Empire Command Center",
  description:
    "Your AI business command centre: lead finding and CRM, posts with images, a voice assistant in 12 languages, market scans, Job Radar, revenue tracking, and 24/7 website SEO and legal checks. Start free.",
  applicationName: "Titan Omega",
  manifest: "/manifest.webmanifest",
  // Without a canonical, ranking splits between the custom domain and the
  // *.hf.space origin behind it.
  alternates: { canonical: SITE },
  icons: {
    icon: "/favicon.png",
    apple: "/icons/apple-touch-icon.png",
  },
  appleWebApp: {
    capable: true,
    title: "Titan Omega",
    statusBarStyle: "black-translucent",
  },
  // `appleWebApp.capable` only emits `apple-mobile-web-app-capable`, which Chrome
  // warns is deprecated in favour of the standard name. Both are shipped: iOS
  // Safari still reads the Apple tag for standalone mode, and dropping it would
  // break "Add to Home Screen" there.
  other: {
    "mobile-web-app-capable": "yes",
  },
  openGraph: {
    type: "website",
    url: SITE,
    siteName: "Titan Omega",
    title: "Titan Omega — Empire Command Center",
    description:
      "Your AI business command centre: lead finding and CRM, posts with images, a voice assistant in 12 languages, market scans, Job Radar, revenue tracking, and 24/7 website SEO and legal checks. Start free.",
  },
};

export const viewport: Viewport = {
  themeColor: "#05070d",
  // The command centre is edge-to-edge; without this the 3D canvas stops at the
  // notch on a phone.
  viewportFit: "cover",
  width: "device-width",
  initialScale: 1,
};

/**
 * Product schema, rendered server-side into the static export.
 *
 * Titan's audit flags missing structured data as critical on client sites,
 * and the schema on /pricing is injected by the FastAPI route, which never
 * touches this Next-rendered page.
 *
 * No prices here: the priced Offers live on /pricing, generated by the server
 * from the live plan table. Static copies here could drift from what's
 * charged.
 */
const PRODUCT_SCHEMA = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "SoftwareApplication",
      name: "Titan Omega",
      applicationCategory: "BusinessApplication",
      operatingSystem: "Web",
      url: SITE,
      description:
        "Your AI business command centre: lead finding and CRM, posts with images, a voice assistant in 12 languages, market scans, Job Radar, revenue tracking, and 24/7 website SEO and legal checks. Start free.",
      featureList: [
        "Lead finding and CRM pipeline",
        "Social post drafts with images and a ready-to-post queue",
        "Ask Titan by voice or text in 12 languages",
        "Market scan and Job Radar",
        "Revenue and expense tracking",
        "Technical SEO audit",
        "Local ranking factor scoring on published 2026 weights",
        "Legal compliance across 9 jurisdictions (Impressum / §5 DDG, GDPR consent)",
        "24/7 monitoring with regression alerts",
        "Client-ready PDF reports",
      ],
    },
    { "@type": "Organization", name: "Titan Omega", url: SITE, logo: `${SITE}/icons/icon-512.png` },
    { "@type": "WebSite", name: "Titan Omega", url: SITE },
  ],
};

/**
 * Recovers a page whose app scripts failed to load.
 *
 * If a script from /_next/static/ fails (an upstream outage, or a broken
 * copy left in an older service worker's cache), React never starts and the
 * page sits on "Booting the command centre..." for good. This drops every
 * service worker and cache for the site and reloads, at most twice per
 * session. The 20-second timer covers a failure that happened before this
 * listener existed. RegisterSW sets `__titanBooted` once the app is running.
 *
 * Plain ES5 on purpose: it has to run before, and without, the app bundle.
 */
const BOOT_WATCHDOG = `(function () {
  var KEY = "titan-boot-recoveries";
  var started = false;
  function recover() {
    if (started || window.__titanBooted) return;
    started = true;
    var tries = 0;
    try { tries = Number(sessionStorage.getItem(KEY)) || 0; } catch (e) {}
    if (tries >= 2) return;
    try { sessionStorage.setItem(KEY, String(tries + 1)); } catch (e) {}
    var jobs = [];
    try {
      if (navigator.serviceWorker) {
        jobs.push(navigator.serviceWorker.getRegistrations().then(function (rs) {
          return Promise.all(rs.map(function (r) { return r.unregister(); }));
        }));
      }
      if (window.caches) {
        jobs.push(caches.keys().then(function (ks) {
          return Promise.all(ks.map(function (k) { return caches.delete(k); }));
        }));
      }
    } catch (e) {}
    Promise.all(jobs).catch(function () {}).then(function () {
      setTimeout(function () { location.reload(); }, 1500);
    });
  }
  window.addEventListener("error", function (e) {
    var t = e.target;
    if (t && t.tagName === "SCRIPT" && String(t.src).indexOf("/_next/static/") !== -1) recover();
  }, true);
  setTimeout(recover, 20000);
})();`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: BOOT_WATCHDOG }} />
      </head>
      <body className="min-h-screen antialiased">
        {children}
        <RegisterSW />
        <script
          type="application/ld+json"
          // Next escapes this for us; the object is a literal, never user input.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(PRODUCT_SCHEMA) }}
        />
      </body>
    </html>
  );
}
