name: Sync to Hugging Face Hub

on:
  push:
    branches: [main] # Set this to your default branch
  workflow_dispatch: # Allows you to run it manually

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://careermind2026:$HF_TOKEN@huggingface.co/spaces/careermind2026/project-titan-omega main
